<a href="https://colab.research.google.com/github/dominicwooldridge/GSB-S544/blob/Practice-Activities/PA_3_1_Iteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

0. Load the `penguins` dataset from the `palmerpenguins` library, as well as any other libraries you need.

In [3]:
!pip install palmerpenguins

Collecting palmerpenguins
  Downloading palmerpenguins-0.1.4-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from palmerpenguins) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from palmerpenguins) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->palmerpenguins) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->palmerpenguins) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)
Downloading palmerpenguins-0.1.4-py3-none-any.whl (17 kB)
Installing collected packages: palmerpenguins
Successfully installed palmerpenguins-0.1.4

In [4]:
import numpy as np
import pandas as pd
import palmerpenguins

1. Write a function that takes in information about a penguin, and returns one of the following definitions:

*   "Big Mouth Billy": Male penguins with bill length times bill depth greater than 800.
*   "Dainty Daisy": Female penguins with flipper length less than 5% of body mass.
*   "Average Adelie:" Any Adelie penguins that do not fall into either category.
*   "Other": Any penguins that do not fall into any of the categories.

In [7]:
penguins = palmerpenguins.load_penguins()
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [8]:
def big_mouth_billy(penguins):
  condition = (penguins["sex"] == "male") & (penguins["bill_length_mm"] * penguins["bill_depth_mm"] > 800)
  return penguins[condition]

In [9]:
def dainty_daisy(penguins):
  condition = (penguins["sex"] == "female") & (penguins["flipper_length_mm"] < 0.05 * penguins["body_mass_g"])
  return penguins[condition]

In [20]:
def average_adelie(penguins):
  condition_billy = (penguins["sex"] == "male") & (penguins["bill_length_mm"] * penguins["bill_depth_mm"] > 800)
  condition_daisy = (penguins["sex"] == "female") & (penguins["flipper_length_mm"] < 0.05 * penguins["body_mass_g"])
  condition_adelie = (penguins["species"] == "Adelie") & ~(condition_billy) & ~(condition_daisy)
  return penguins[condition_adelie]

In [21]:
def other(penguins):
  condition_billy = (penguins["sex"] == "male") & (penguins["bill_length_mm"] * penguins["bill_depth_mm"] > 800)
  condition_daisy = (penguins["sex"] == "female") & (penguins["flipper_length_mm"] < 0.05 * penguins["body_mass_g"])
  condition_adelie = (penguins["species"] == "Adelie") & ~(condition_billy) & ~(condition_daisy)
  condition_other = ~(condition_billy) & ~(condition_daisy) & ~(condition_adelie)
  return penguins[condition_other]

2. Use an iterable function to create a new variable called `category_name` that adds these labels.

In [18]:
def category_name(row):
  if (row["sex"] == "male") & (row["bill_length_mm"] * row["bill_depth_mm"] > 800):
    return "Big Mouth Billy"

  elif (row["sex"] == "female") & (row["flipper_length_mm"] < 0.05 * row["body_mass_g"]):
    return "Dainty Daisy"

  elif (row["species"] == "Adelie"):
    return "Average Adelie"

  else:
    return "Other"

penguins["category_name"] = penguins.apply(category_name, axis=1)

3. Run the following code to find the counts for each type.

In [19]:
penguins.value_counts("category_name")

category_name
Average Adelie     127
Other               84
Big Mouth Billy     71
Dainty Daisy        62
Name: count, dtype: int64